//// <auto-generated />
//using System;
//using CrayonCloudSale.Infrastructure.Data;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Metadata;
//using Microsoft.EntityFrameworkCore.Migrations;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

//#nullable disable

//namespace CrayonCloudSale.Api.Migrations
//{
//    [DbContext(typeof(CloudSaleContext))]
//    [Migration("20241122000548_InitialCreate")]
//    partial class InitialCreate
//    {
//        /// <inheritdoc />
//        protected override void BuildTargetModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "9.0.0")
//                .HasAnnotation("Relational:MaxIdentifierLength", 128);

//            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

//            modelBuilder.Entity("CrayonCloudSale.Infrastructure.Data.Models.Account", b =>
//                {
//                    b.Property<long>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("bigint");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

//                    b.Property<DateTime?>("ChangeDate")
//                        .HasColumnType("datetime2");

//                    b.Property<DateTime>("CreateDate")
//                        .HasColumnType("datetime2");

//                    b.Property<long>("CustomerId")
//                        .HasColumnType("bigint");

//                    b.Property<string>("Name")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("Id");

//                    b.HasIndex("CustomerId");

//                    b.ToTable("Accounts");
//                });

//            modelBuilder.Entity("CrayonCloudSale.Infrastructure.Data.Models.Customer", b =>
//                {
//                    b.Property<long>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("bigint");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

//                    b.Property<DateTime?>("ChangeDate")
//                        .HasColumnType("datetime2");

//                    b.Property<DateTime>("CreateDate")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("Name")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("Id");

//                    b.ToTable("Customers");
//                });

//            modelBuilder.Entity("CrayonCloudSale.Infrastructure.Data.Models.PurchasedSoftware", b =>
//                {
//                    b.Property<long>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("bigint");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

//                    b.Property<long>("AccountId")
//                        .HasColumnType("bigint");

//                    b.Property<DateTime?>("ChangeDate")
//                        .HasColumnType("datetime2");

//                    b.Property<DateTime>("CreateDate")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("Name")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<int>("Quantity")
//                        .HasColumnType("int");

//                    b.Property<int>("State")
//                        .HasColumnType("int");

//                    b.Property<DateTime>("ValidTo")
//                        .HasColumnType("datetime2");

//                    b.HasKey("Id");

//                    b.HasIndex("AccountId");

//                    b.ToTable("PurchasedSoftwares");
//                });

//            modelBuilder.Entity("CrayonCloudSale.Infrastructure.Data.Models.Account", b =>
//                {
//                    b.HasOne("CrayonCloudSale.Infrastructure.Data.Models.Customer", "Customer")
//                        .WithMany("Accounts")
//                        .HasForeignKey("CustomerId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("Customer");
//                });

//            modelBuilder.Entity("CrayonCloudSale.Infrastructure.Data.Models.PurchasedSoftware", b =>
//                {
//                    b.HasOne("CrayonCloudSale.Infrastructure.Data.Models.Account", "Account")
//                        .WithMany("PurchasedSoftwares")
//                        .HasForeignKey("AccountId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("Account");
//                });

//            modelBuilder.Entity("CrayonCloudSale.Infrastructure.Data.Models.Account", b =>
//                {
//                    b.Navigation("PurchasedSoftwares");
//                });

//            modelBuilder.Entity("CrayonCloudSale.Infrastructure.Data.Models.Customer", b =>
//                {
//                    b.Navigation("Accounts");
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
